export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";


export const FETCH_QUIZ_REQUEST = "FETCH_QUIZ_REQUEST";
export const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS";
export const FETCH_QUIZ_FAILURE = "FETCH_QUIZ_FAILURE";


export const SUBMIT_ANSWER = "SUBMIT_ANSWER";
export const SKIP_QUESTION = "SKIP_QUESTION";
export const RESET_QUIZ = "RESET_QUIZ";
export const NEXT_QUESTION="NEXT_QUESTION"